### ISSUE TITLE
Name in main screen

### ISSUE THREAD

**Issue by Stoneshop** [computermuseumarnhem/cma_inventoryapp#1]
Name samengesteld uit Manufacturer + Model, tenzij overschreven vanuit details
Op hoofdscherm alleen Name tonen

Voorbeeld:
Mfg: Olivetti, Model: M19 -> Name: Olivetti M19
Mfg: Siemens, Model: T1000 -> Name: PTT Telescript 12

**Comment by vandenzel** [comment]
Check het eens? Zou nu actief moeten zijn. Zowel in de list als in de losse item-views (niet in het veld, wel in de grote letters)
