### ISSUE TITLE
Internal server error editing item

### ISSUE THREAD

**Issue by Stoneshop** [computermuseumarnhem/cma_inventoryapp#20]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

item#341, Category: Storage -> Storage|Tape

**Comment by vandenzel** [comment]
label wasn't unique. building check.

**Comment by vandenzel** [comment]
fixed.

**Comment by vandenzel** [comment]
empty labels are translated to None (null in db). Unicity validation is done and "save" won't allow non-unique labels.

**Comment by Stoneshop** [comment]
OK
