### ISSUE TITLE
Label field can not be left empty when editing item without label

### ISSUE THREAD

**Issue by Stoneshop** [computermuseumarnhem/cma_inventoryapp#23]
Label field can not be left empty and needs to be unique when editing item that has not been labelled yet

**Comment by vandenzel** [comment]
Fixed that in development. Now if the label is empty it will be set to null instead of empty string. And null doesn't count for uniqueness.

**Comment by vandenzel** [comment]
werkt nu

**Comment by Stoneshop** [comment]
Inderdaad
