### ISSUE TITLE
After sorting (any column) selecting an item does not open the details page

### ISSUE THREAD

**Issue by Stoneshop** [computermuseumarnhem/cma_inventoryapp#25]
Back to home, then index to restore default sort, selecting works again.

**Comment by vandenzel** [comment]
Known bug. Copy/Pasta from StackOverflow doesn't work always.

**Comment by vandenzel** [comment]
fixed by removing bootstrap-table and implementing ordering server-side.

**Comment by Stoneshop** [comment]
Appears fixed
