### ISSUE TITLE
Replace id column with label

### ISSUE THREAD

**Issue by ghost** [computermuseumarnhem/cma_inventoryapp#8]
We now have two 'ids' for entries, the 'id' (which presumably is an internal database thingy auto assigned) and the real item id (the 42xxxxxx number). This is confusing.

Suggestion: just get rid of the id column, give everything a label id (which is the 'collection id' and the primary key), and add a boolean field 'labelled'.

**Comment by vandenzel** [comment]
Because the label field is nullable (but unique and indexed) i'd opted for a separate primary key. I put it in the templates actually just for reference. It will disappear.

**Comment by vandenzel** [comment]
I've removed the ID column in the list, and field in the item pages -- not from the database.

**Comment by ghost** [comment]
The nullable problem is easily solved by making it non-nullable :) But anyway, at least its not shown anymore, wfm
